#!/usr/bin/env python3
import os, json, requests, argparse
from bs4 import BeautifulSoup
from datetime import datetime, timedelta
import pandas as pd

def get_caldata(date, url='https://www.earningswhispers.com'):
    try:
        datetime.strptime(date, '%Y%m%d')
    except:
        print('Date format is incorrect')
        os._exit(1)
    res = requests.get(f"{url}/api/caldata/{date}", headers={
        'cookie': '.AspNetCore.Antiforgery.gLLQ8_-gK9o=IAMAI; hidenonconfirmed=0; .AspNet.Consent=yes',
        'referer': url, 'User-Agent': 'IAMAI'
    })
    if not res.ok:
        print('API response is invalid')
        os._exit(2)
    return json.loads(res.content)

if __name__ == '__main__':
    arg = argparse.ArgumentParser()
    arg.add_argument('--verbose', default=False, action='store_true', help='Verbose output')
    arg.add_argument('--start', default=datetime.now().strftime('%Y%m%d'), help='From (default: %(default)s)')
    arg.add_argument('--end', default=(datetime.now() + timedelta(days=7)).strftime('%Y%m%d'), help='To (default: %(default)s)')
    args = arg.parse_args()

    raw_dates = pd.date_range(args.start, args.end, freq='D').to_series()
    df = pd.DataFrame(raw_dates, columns=['dates'])
    df['dow'] = raw_dates.dt.dayofweek
    dates = list(map(lambda d: d.astype(str).split('T')[0].replace('-',''), df[df['dow']<5].dates.values))
    cdf = pd.concat(list(map(pd.DataFrame, map(get_caldata, dates)))).reset_index(drop=True)